CREATE TABLE CUSTOMER (ID varchar(255),NAME varchar(255),SURNAME varchar(255),FISCAL_CODE varchar(255),ANDRESS varchar(255))

INSERT INTO CUSTOMER (ID, NAME, SURNAME, FISCAL_CODE, ANDRESS) VALUES ('1', 'N','S','CF','A')
