CREATE TABLE CUSTOMER (ID varchar(255),NAME varchar(255),SURNAME varchar(255),FISCAL_CODE varchar(255),ANDRESS varchar(255))
CREATE TABLE DEVICE (ID varchar(255),ID_USER varchar(255),STATUS varchar(255))

INSERT INTO CUSTOMER (ID, NAME, SURNAME, FISCAL_CODE, ANDRESS) VALUES ('idCustomer1', 'N','S','CF','A')
INSERT INTO DEVICE (ID, ID_USER, STATUS) VALUES ('idDevice1', 'idCustomer1','ACTIVE')
